---
driver_plugin: vagrant
driver_config:
  customize:
    memory: 1024

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04-nochef
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    require_chef_omnibus: 11.6.0
  run_list:
  - recipe[apt]

suites:
- name: single-node
  run_list:
    - recipe[hipsnip-elasticsearch_test::single_node]
    - recipe[minitest-handler]
- name: cluster-lwrp
  run_list:
    - recipe[hipsnip-elasticsearch_test::cluster_lwrp]
    - recipe[minitest-handler]